//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : AdaptadorUPMAuthenticator.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;

import servidor.ObtencionDeRol;
import servidor.UPMUsers;


public class AdaptadorUPMAuthenticator implements IAdaptadorAutenticador {

    @Override
    public RolUPM validarEnUPM(String email) {
        try {
            UPMUsers rol = ObtencionDeRol.get_UPM_AccountRol(email);
            if (rol == null) {
                return RolUPM.INEXISTENTE;
            }

            switch (rol.name()) {
                case "ALUMNO":
                    return RolUPM.ESTUDIANTE;
                case "PDI":
                    return RolUPM.PDI;
                case "PAS":
                    return RolUPM.PAS;
                default:
                    return RolUPM.INEXISTENTE;
            }

        } catch (Exception e) {
            System.err.println("Error de conexión con UPM Authenticator: " + e.getMessage());
            return RolUPM.INEXISTENTE;
        }
    }

}
