//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : AdaptadorUPMAuthenticator.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;



public class AdaptadorUPMAuthenticator implements IAdaptadorAutenticador {
	private ExternalLDAP servicioExterno;
	public RolUPM validarEnUPM(String email) {
	
	}
	
	public RolUPM validarEnUPM(String email);
}
