//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : ControladorUsuarios.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//

package es.upm.etsisi.poo;

import java.util.HashMap;

public class ControladorUsuarios implements IControladorUsuarios {
    private IUsuarioDAO dao;
    private IAdaptadorAutenticador autenticador;
    private ValidadorNick validadorNick;

    public ControladorUsuarios(IUsuarioDAO dao, IAdaptadorAutenticador autenticador) {
        this.dao = dao;
        this.autenticador = autenticador;
        this.validadorNick = new ValidadorNick();
    }

    @Override
    public boolean registrarParticipante(HashMap datos) {
        String nick = (String) datos.get("nick");
        String nombre = (String) datos.get("nombre");
        String correo = (String) datos.get("correo");
        String contrasena = (String) datos.get("contrasena");
        String dni = (String) datos.get("dni");
        String tarjeta = (String) datos.get("tarjetaCredito");

        if (!validarNick(nick) || !validarContrasena(contrasena)) {
            return false;
        }
        if (dao.buscarPorEmail(correo) != null || dao.existeNick(nick)) {
            return false; // Usuario ya registrado
        }

        Usuario nuevoParticipante = null;
        if (correo.endsWith("upm.es")) {
            RolUPM rol = determinarRolUPM(correo);
            if (rol == RolUPM.ESTUDIANTE) {
                String matricula = (String) datos.get("matricula");
                nuevoParticipante = new EstudianteUPM(nick, nombre, correo, contrasena, dni, tarjeta, matricula);
            } else if (rol == RolUPM.PDI || rol == RolUPM.PAS) {
                int antiguedad = 0;
                try {
                    String antiStr = (String) datos.get("antiguedad");
                    if (antiStr != null && !antiStr.isEmpty()) {
                        antiguedad = Integer.parseInt(antiStr);
                    }
                } catch (NumberFormatException e) {
                    return false;
                }

                nuevoParticipante = new PersonalUPM(nick, nombre, correo, contrasena, dni, tarjeta, antiguedad);
            } else {
                return false;
            }
        } else {
            nuevoParticipante = new ParticipanteExterno(nick, nombre, correo, contrasena, dni, tarjeta);
        }
        return dao.guardarUsuario(nuevoParticipante);
    }

    @Override
    public boolean registrarInstructor(HashMap datos, HashMap pago) {

        // solo los administradores pueden crear instructores.
        Usuario usuarioLogueado = SesionActiva.getInstancia().getUsuario();
        if (!(usuarioLogueado instanceof Administrador)) {
            return false; // si no hay nadie logueado o el que está no es administrador, se deniega el registro.
        }

        String nick = (String) datos.get("nick");
        String nombre = (String) datos.get("nombre");
        String correo = (String) datos.get("correo");
        String contrasena = (String) datos.get("contrasena");
        String dni = (String) datos.get("dni");
        String iban = (String) pago.get("iban");

        if (!validarNick(nick) || !validarContrasena(contrasena)) {
            return false;
        }
        if (dao.buscarPorEmail(correo) != null || dao.existeNick(nick)) {
            return false;
        }

        Usuario nuevoInstructor = new Instructor(nick, nombre, correo, contrasena, dni, iban);
        return dao.guardarUsuario(nuevoInstructor);
    }
    @Override
    public boolean darBajaInstructor(String nick) {
        Usuario usuarioLogueado = SesionActiva.getInstancia().getUsuario();
        // damos permiso si es admin O si es el propio usuario borrándose a sí mismo
        if (usuarioLogueado instanceof Administrador || usuarioLogueado.getNick().equals(nick)) {
            return dao.eliminarUsuario(nick);
        }
        return false;
    }

    @Override
    public boolean darBajaParticipante(String nick) {
        Usuario usuarioLogueado = SesionActiva.getInstancia().getUsuario();
        // damos permiso si es admin O si es el propio usuario borrándose a sí mismo
        if (usuarioLogueado instanceof Administrador || usuarioLogueado.getNick().equals(nick)) {
            return dao.eliminarUsuario(nick);
        }
        return false;
        //return dao.eliminarUsuario(nick);
    }


    @Override
    public boolean login(String email, String contrasena) {
        Usuario usuario = dao.buscarPorEmail(email);
        if (usuario != null && usuario.verificarContrasena(contrasena)) {
            SesionActiva.getInstancia().setUsuario(usuario);
            return true;
        }
        return false;
    }

    public boolean validarNick(String nick) {
        return validadorNick.validarNick(nick);
    }

    public boolean validarContrasena(String contrasena) {
        if (contrasena == null || contrasena.length() < 12) {
            return false;
        }

        boolean tieneMayus = false;
        boolean tieneMinus = false;
        boolean tieneNum = false;

        for (char c : contrasena.toCharArray()) {
            if (Character.isUpperCase(c)){
                tieneMayus = true;
            } else if (Character.isLowerCase(c)){
                tieneMinus = true;
            } else if (Character.isDigit(c)){
                tieneNum = true;
            }
        }
        return tieneMayus && tieneMinus && tieneNum;
    }


    @Override
    public RolUPM determinarRolUPM(String email) {
        return autenticador.validarEnUPM(email);
    }
}
