//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : ControladorUsuarios.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//




public class ControladorUsuarios implements IControladorUsuario {
	private IUsuarioDAO dao;
	private IAdaptadorAutenticador autenticador;
	public boolean registrarParticipante(HashMap datos) {
	
	}
	
	public boolean registrarInstructor(HashMap datos) {
	
	}
	
	public boolean login(String email, String contraseña) {
	
	}
	
	public boolean validarNick(String nick) {
	
	}
	
	public boolean validarContraseña(String contraseña) {
	
	}
	
	public RolUPM determinarTipoMiembroUPM(String email) {
	
	}
	
	public boolean login(String email, String pass);
	
	public boolean registrarParticipante(HashMap datos);
	
	public boolean registrarInstructor(HashMap datos, HashMap pago);
}
