//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : ControladorUsuarios.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//

package es.upm.etsisi.poo;
import java.util.HashMap;

public class ControladorUsuarios implements IControladorUsuarios {
	private IUsuarioDAO dao;
	private IAdaptadorAutenticador autenticador;
	public boolean registrarParticipante(HashMap datos) {
	
	}
	
	public boolean registrarInstructor(HashMap datos) {
	
	}
	
	public boolean login(String email, String contrasena) {
	
	}
	
	public boolean validarNick(String nick) {
	
	}
	
	public boolean validarContrasena(String contrasena) {
	
	}
	
	public RolUPM determinarTipoMiembroUPM(String email) {
	
	}
	
	public boolean login(String email, String pass);

	public boolean registrarParticipante(HashMap datos);

	public boolean registrarInstructor(HashMap datos, HashMap pago);
}
