//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : IAdaptadorAutenticador.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//




public interface IAdaptadorAutenticador {
	public RolUPM validarEnUPM(String email);
}
