//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : IControladorUsuarios.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;



public interface IControladorUsuarios {
	public boolean login(String email, String pass);
	public boolean registrarParticipante(HashMap datos);
	public boolean registrarInstructor(HashMap datos, HashMap pago);
}
