//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : IControladorUsuarios.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;


import java.util.HashMap;

public interface IControladorUsuarios {
    boolean login(String email, String pass);

    boolean registrarParticipante(HashMap<String, String> datos);

    boolean registrarInstructor(HashMap datos, HashMap pago);

    boolean validarNick(String nick);

    boolean validarContrasena(String contrasena);
}
