//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : IDatosUsuaio.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;



public interface IDatosUsuaio {
	public String getCorreo();
}
