//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : IUsuarioDAO.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;



public interface IUsuarioDAO {
	public boolean guardarUsuario(Usuario u);
	public Usuario buscarPorEmail(String email);
	public boolean existeNick(String nick);
	public boolean actualizarUsuario(String nick, Usuario u);
}
