//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : IUsuarioDAO.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;




public interface IUsuarioDAO {

    boolean guardarUsuario(Usuario u);

    Usuario buscarPorEmail(String email);

    boolean existeNick(String nick);

    boolean eliminarUsuario(String nick);

    boolean actualizarUsuario(String nick, Usuario u);
}
