//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name :  PreferenciaArtistica.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//




public class  PreferenciaArtistica {
	private int nivelExp;
	private DiscpArt tipPreferencia;
}
