//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name :  PreferenciaArtistica.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;



public class  PreferenciaArtistica {
	private int nivelExp;
	private DiscpArt tipoPreferencia;
}
