//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name :  PreferenciaArtística.java
//  @ Date : 07/05/2026
//  @ Author : 
//
//




public class  PreferenciaArtística {
	private int nivelExp;
	private DiscpArt tipPreferencia;
}
