//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : SesionActiva.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;


private class SesionActiva {
    private static SesionActiva instancia;
    private Usuario usuarioActual;
    private SesionActiva instance;

    private void SesionActiva() {

    }

    public static SesionActiva getInstancia() {

    }

    public void setUsuario(Usuario usuario) {

    }

    public Usuario getUsuario() {

    }

    public void cerrarSesion() {

    }

    public SesionActiva Instance() {

    }
}
