//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : SesionActiva.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//
package es.upm.etsisi.poo;

public class SesionActiva {

    private static SesionActiva instancia;
    private Usuario usuarioActual;

    private SesionActiva() {
        this.usuarioActual = null;
    }

    public static SesionActiva getInstancia() {
        if (instancia == null) {
            instancia = new SesionActiva();
        }

        return instancia;
    }

    public void setUsuario(Usuario usuario) {
        this.usuarioActual = usuario;
    }

    public Usuario getUsuario() {
        return usuarioActual;
    }

    public void cerrarSesion() {
        this.usuarioActual = null;
    }

    public SesionActiva Instance() {
        return getInstancia();
    }
}