//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : Usuario.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//




public abstract class Usuario implements IDatosUsuaio {
	private String nick;
	private String nombre;
	private String correo;
	private String contraseñaCifrada;
	public void Usuario(String nick, String nombre, String correo, String contraseña) {
	
	}
	
	public String getNick() {
	
	}
	
	public String getNombre() {
	
	}
	
	public String getCorreo() {
	
	}
	
	public void setContraseña(String nuevaContraseña) {
	
	}
	
	public boolean verificarContraseña(String contraseña) {
	
	}
	
	private String cifrarContraseña(String contraseña) {
	
	}
	
	public String getCorreo();
}
