//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : Usuario.java
//  @ Date : 07/05/2026
//  @ Author : 
//
//




public abstract class Usuario {
	private String nick;
	private String nombre;
	private String correo;
	private String contrase?aCifrada;
	public void Usuario(String nick, String nombre, String correo, String contrase?a) {
	
	}
	
	public String getNick() {
	
	}
	
	public String getNombre() {
	
	}
	
	public void getEmail() {
	
	}
	
	public void setContrase?a(String nuevaContrase?a) {
	
	}
	
	public boolean verificarContrase?a(String contrase?a) {
	
	}
}
