//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : UsuarioFichero.java
//  @ Date : 07/05/2026
//  @ Author : 
//
//




public class UsuarioFichero implements IUsuarioDAO {
	private String rutaFichero;
	private String serializar(Usuario u) {
	
	}
	
	public Usuario deserializar(String linea) {
	
	}
	
	public boolean guardarUsuario(Usuario u) {
	
	}
	
	public Usuario buscarPorEmail(String email) {
	
	}
	
	public boolean existeNick(String nick) {
	
	}
	
	public boolean guardarUsuario(Usuario u);
	
	public Usuario buscarPorEmail(String email);
	
	public boolean existeNick(String nick);
}
