//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : ValidadorNick.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//




public class ValidadorNick {
	private List<String> terminosConflictivos;
	public boolean validarNick(String nick) {
	
	}
}
