//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : VistaUsuariosCLI.java
//  @ Date : 07/05/2026
//  @ Author : 
//
//




public class VistaUsuariosCLI {
	private IControladorUsuarios controlador;
	public void mostrarMenuPrincipal() {
	
	}
	
	public HashMap pedirDatosRegistro() {
	
	}
	
	public HashMap pedirDatosPago() {
	
	}
	
	public void mostrarMensaje(String mensaje) {
	
	}
}
