//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : VistaEspaciosCLI.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//




public class VistaEspaciosCLI {
	private IControladorEspacios controlador;
	public void mostrarMenuEspacios() {
	
	}
	
	public HashMap pedirDatosEspacio() {
	
	}
	
	public HashMap pedirDatosEquipamiento() {
	
	}
}
