//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : VistaUsuariosCLI.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//

package es.upm.etsisi.poo;

import java.util.HashMap;
import java.util.Scanner;

/**
 * Vista CLI para alta y acceso de usuarios.
 *
 * Responsabilidad: pedir datos, mostrar mensajes y llamar al controlador.
 * No debe crear usuarios, validar reglas de negocio ni acceder a ficheros/DAOs.
 */
public class VistaUsuariosCLI {
    private final IControladorUsuarios controlador;
    private final Scanner scanner;

    public VistaUsuariosCLI(IControladorUsuarios controlador) {
        this.controlador = controlador;
        this.scanner = new Scanner(System.in);
    }

    public void mostrarMenuPrincipal() {
        boolean volver = false;

        while (!volver) {
            System.out.println();
            System.out.println("--- Gestion de usuarios ---");
            System.out.println("1 Iniciar sesion");
            System.out.println("2 Registrar participante");
            // eliminamos la opcion 3 de aqui
            System.out.println("0 Volver");
            System.out.print("Selecciona una opcion: ");

            String opcion = scanner.nextLine().trim();

            switch (opcion) {
                case "1":
                    procesarLogin();
                    break;
                case "2":
                    procesarRegistroParticipante();
                    break;
                case "0":
                    volver = true;
                    break;
                default:
                    mostrarMensaje("Opcion no valida. Intentalo de nuevo.");
            }
        }
    }

    public HashMap<String, String> pedirDatosRegistro() {
        HashMap<String, String> datos = new HashMap<>();

        datos.put("nombre", pedirTexto("Nombre completo: "));
        datos.put("nick", pedirTexto("Nick (4-12 caracteres): "));
        datos.put("correo", pedirTexto("Email: "));

        mostrarMensaje("La contraseña debe tener al menos 12 caracteres, incluir una mayúscula, una minúscula y un número.");
        datos.put("contrasena", pedirTexto("Contraseña: "));

        datos.put("dni", pedirTexto("DNI: "));

        return datos;
    }

    public HashMap<String, String> pedirDatosPago() {
        HashMap<String, String> pago = new HashMap<>();

        pago.put("titular", pedirTexto("Titular de la tarjeta: "));
        pago.put("numeroTarjeta", pedirTexto("Numero de tarjeta: "));
        pago.put("fechaCaducidad", pedirTexto("Fecha de caducidad MM/AA: "));
        pago.put("cvv", pedirTexto("CVV: "));

        return pago;
    }

    public void mostrarMensaje(String mensaje) {
        System.out.println(mensaje);
    }

    private void procesarLogin() {
        String email = pedirTexto("Email: ");
        String contrasena = pedirTexto("Contrasena: ");

        boolean correcto = controlador.login(email, contrasena);

        if (correcto) {
            mostrarMensaje("Sesion iniciada correctamente.");
            mostrarMenuSesionIniciada();
        } else {
            mostrarMensaje("No se pudo iniciar sesion. Revisa email y contrasena.");
        }
    }
    private void mostrarMenuSesionIniciada() {
        boolean cerrarSesion = false;
        Usuario usuarioLogueado = SesionActiva.getInstancia().getUsuario();
        boolean esAdmin = usuarioLogueado instanceof Administrador;

        while (!cerrarSesion) {
            System.out.println();

            if (esAdmin) {
                System.out.println("--- Panel de Administrador ---");
                System.out.println("1 Registrar instructor");
                System.out.println("2 Dar de baja instructor");
                System.out.println("3 Dar de baja participante");
            } else {
                System.out.println("--- Panel de Usuario ---");
                System.out.println("1 Ver mi perfil (proximamente)");
                System.out.println("2 Apuntarse a actividad (proximamente)");
                System.out.println("3 Darme de baja");
            }
            System.out.println("0 Cerrar sesion");
            System.out.print("Selecciona una opcion: ");

            String opcion = scanner.nextLine().trim();

            if (esAdmin) {
                switch (opcion) {
                    case "1":
                        procesarRegistroInstructor();
                        break;
                    case "2":
                        procesarBajaUsuario("instructor");
                        break;
                    case "3":
                        procesarBajaUsuario("participante");
                        break;
                    case "0":
                        cerrarSesion = true;
                        mostrarMensaje("Cerrando sesion...");
                        SesionActiva.getInstancia().cerrarSesion();
                        break;
                    default:
                        mostrarMensaje("Opcion no valida.");
                }
            } else {
                switch (opcion) {
                    case "1":
                    case "2":
                        mostrarMensaje("Funcionalidad en desarrollo...");
                        break;
                    case "3":
                        String nickActual = usuarioLogueado.getNick();
                        if (usuarioLogueado instanceof Instructor) {
                            controlador.darBajaInstructor(nickActual);
                        } else {
                            controlador.darBajaParticipante(nickActual);
                        }
                        mostrarMensaje("Te has dado de baja correctamente. ¡Hasta pronto!");
                        cerrarSesion = true;
                        SesionActiva.getInstancia().cerrarSesion();
                        break;
                    case "0":
                        cerrarSesion = true;
                        mostrarMensaje("Cerrando sesion...");
                        SesionActiva.getInstancia().cerrarSesion();
                        break;
                    default:
                        mostrarMensaje("Opcion no valida.");
                }
            }
        }
    }

    private void procesarRegistroParticipante() {
        HashMap<String, String> datos = pedirDatosRegistro();

        HashMap<String, String> pago = pedirDatosPago();

        String tarjetaCompleta = pago.get("numeroTarjeta") + " - " + pago.get("titular");
        datos.put("tarjetaCredito", tarjetaCompleta);

        if (datos.get("correo").endsWith("upm.es")) {
            mostrarMensaje("Se ha detectado un correo institucional UPM. Consultando rol...");
            RolUPM rol = controlador.determinarRolUPM(datos.get("correo"));

            if (rol == RolUPM.ESTUDIANTE) {
                mostrarMensaje("Rol detectado: Estudiante UPM.");
                datos.put("matricula", pedirTexto("Numero de matricula: "));
            } else if (rol == RolUPM.PDI || rol == RolUPM.PAS) {
                mostrarMensaje("Rol detectado: Personal UPM (PDI/PAS).");
                datos.put("antiguedad", pedirTexto("Anios de antiguedad: "));
            } else {
                mostrarMensaje("Error: El correo UPM no está reconocido en el sistema.");
                return;
            }
        }

        boolean correcto = controlador.registrarParticipante(datos);

        if (correcto) {
            mostrarMensaje("Participante registrado correctamente.");
        } else {
            mostrarMensaje("Error: No se pudo registrar. Revisa el formato de la contraseña, que el nick no contenga palabras prohibidas o que el correo no este ya en uso.");
        }
    }

    private void procesarRegistroInstructor() {
        HashMap<String, String> datos = pedirDatosRegistro(); // pedimos nombre, nick, correo, pass y DNI

        HashMap<String, String> pago = new HashMap<>();
        // pedimos el IBAN en lugar de la tarjeta de crédito
        pago.put("iban", pedirTexto("IBAN (para el ingreso de honorarios): "));

        boolean correcto = controlador.registrarInstructor(datos, pago);

        if (correcto) {
            mostrarMensaje("Instructor registrado correctamente.");
        } else {
            mostrarMensaje("Error: No se pudo registrar el instructor. Revisa los datos introducidos.");
        }
    }
    private void procesarBajaUsuario(String tipo) {
        String nick = pedirTexto("Nick del " + tipo + " a dar de baja: ");
        boolean correcto;

        if (tipo.equals("instructor")) {
            correcto = controlador.darBajaInstructor(nick);
        } else {
            correcto = controlador.darBajaParticipante(nick);
        }

        if (correcto) {
            mostrarMensaje("Usuario dado de baja correctamente.");
        } else {
            mostrarMensaje("Error: No se pudo dar de baja. Revisa que el nick existe.");
        }
    }

    private String pedirTexto(String mensaje) {
        String texto;
        do {
            System.out.print(mensaje);
            texto = scanner.nextLine().trim();
            if (texto.isEmpty()) {
                mostrarMensaje("El campo no puede estar vacio.");
            }
        } while (texto.isEmpty());

        return texto;
    }
}
