//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : VistaPrincipalCLI.java
//  @ Date : 07/05/2026
//  @ Author : 
//
//




public class VistaPrincipalCLI {
	private VistaUsuariosCLI vistaUsuarios;
	private VistaEspaciosCLI vistaEspacios;
	private VistaActividadesCLI vistaActividades;
	private VistaAsociacionesCLI vistaAsociaciones;
	public void iniciarAplicacion() {
	
	}
}
