//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UPMArts
//  @ File Name : VistaPrincipalCLI.java
//  @ Date : 18/05/2026
//  @ Author : 
//
//

package es.upm.etsisi.poo;


public class VistaPrincipalCLI {
	public void iniciarAplicacion() {
	
	}
	
	public void mostrarMenu() {
	
	}
}
